"""HTML email rendering for digest delivery."""

from datetime import datetime, timezone

from jinja2 import Template

from research_digest import __version__
from research_digest.config import AppConfig
from research_digest.models import DigestEntry

_EMAIL_TEMPLATE = Template(
    """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 640px; margin: 0 auto; padding: 20px; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  .meta { color: #666; font-size: 13px; margin-bottom: 24px; }
  .divider { border: none; border-top: 1px solid #e0e0e0; margin: 20px 0; }
  .paper { margin-bottom: 24px; }
  .paper-title { font-size: 16px; font-weight: 600; margin-bottom: 4px; }
  .paper-title a { color: #1a1a1a; text-decoration: none; }
  .paper-title a:hover { color: #2563eb; }
  .paper-info { color: #666; font-size: 12px; margin-bottom: 6px; }
  .paper-summary { font-size: 14px; color: #333; }
  .paper-links { font-size: 12px; margin-top: 6px; }
  .paper-links a { color: #2563eb; text-decoration: none; margin-right: 12px; }
  .footer { color: #999; font-size: 11px; margin-top: 32px; border-top: 1px solid #e0e0e0; padding-top: 12px; }
</style>
</head>
<body>

<h1>{{ title }}</h1>
<div class="meta">{{ generated_at }} &middot; {{ entries | length }} papers</div>

{% for entry in entries %}
<div class="paper">
  <div class="paper-title"><a href="{{ entry.paper.canonical_url }}">{{ entry.paper.title }}</a></div>
  <div class="paper-info">{{ entry.paper.authors | join(', ') }} &middot; {{ entry.paper.published_at.strftime('%b %d') }} &middot; {{ entry.paper.categories | join(', ') }}</div>
  <div class="paper-summary">{{ entry.abstract_excerpt or '' }}</div>
  {% if include_links %}
  <div class="paper-links">
    <a href="{{ entry.paper.canonical_url }}">Abstract</a>
    {% if entry.paper.pdf_url %}<a href="{{ entry.paper.pdf_url }}">PDF</a>{% endif %}
  </div>
  {% endif %}
</div>
{% endfor %}

{% if not entries %}
<p>No papers matched your criteria for this period.</p>
{% endif %}

<div class="footer">
  Generated by research-digest v{{ version }}<br>
  <a href="https://github.com/crlandsc/research-digest">GitHub</a>
</div>

</body>
</html>
""",
    keep_trailing_newline=True,
)

_TEXT_TEMPLATE = Template(
    """\
{{ title }}
{{ generated_at }} - {{ entries | length }} papers

{% for entry in entries %}
{{ entry.rank }}. {{ entry.paper.title }}
   {{ entry.paper.authors | join(', ') }} | {{ entry.paper.published_at.strftime('%b %d') }}
   {{ entry.abstract_excerpt or '' }}
   {{ entry.paper.canonical_url }}

{% endfor %}
{% if not entries %}
No papers matched your criteria for this period.
{% endif %}
Generated by research-digest v{{ version }}
""",
    keep_trailing_newline=True,
)


def render_email(
    entries: list[DigestEntry],
    config: AppConfig,
    total_reviewed: int = 0,
) -> tuple[str, str]:
    """Render digest as (html, plaintext) for email delivery."""
    ctx = dict(
        title=config.digest.title,
        generated_at=datetime.now(timezone.utc).strftime("%B %d, %Y"),
        entries=entries,
        include_links=config.digest.include_links,
        version=__version__,
    )
    return (_EMAIL_TEMPLATE.render(**ctx), _TEXT_TEMPLATE.render(**ctx))
