"""HTML email rendering for digest delivery."""

from collections import OrderedDict
from datetime import datetime, timezone

from jinja2 import Template

from research_digest import __version__
from research_digest.categories import category_label
from research_digest.config import AppConfig
from research_digest.models import DigestEntry


def _group_entries(entries: list[DigestEntry]) -> dict[str, list[DigestEntry]]:
    """Group entries by topic_group, preserving order of first appearance."""
    groups: dict[str, list[DigestEntry]] = OrderedDict()
    for entry in entries:
        groups.setdefault(entry.topic_group, []).append(entry)
    return groups


_EMAIL_TEMPLATE = Template(
    """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0; padding:0; background-color:#f9f9f9;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f9f9f9;">
<tr><td align="center" style="padding:24px 12px;">
<table role="presentation" width="560" cellpadding="0" cellspacing="0" style="max-width:560px; width:100%; background-color:#ffffff; border-radius:8px;">
<tr><td style="padding:32px 28px;">

<!-- Header -->
<h1 style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:24px; font-weight:700; color:#111; margin:0 0 4px 0;">{{ title }}</h1>
<p style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:14px; color:#999; margin:0 0 32px 0;">{{ generated_at }} &middot; {{ total_papers }} paper{{ 's' if total_papers != 1 }}</p>

{% for group_name, group_entries in grouped.items() %}
<!-- Topic Group -->
<p style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:13px; font-weight:700; color:#666; text-transform:uppercase; letter-spacing:0.05em; margin:{% if not loop.first %}8px{% else %}0{% endif %} 0 18px 0; border-bottom:2px solid #111; padding-bottom:6px;">{{ group_name }}</p>

{% for entry in group_entries %}
<p style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:19px; font-weight:700; line-height:1.3; margin:0 0 10px 0;">
  <a href="{{ entry.paper.canonical_url }}" style="color:#111; text-decoration:underline;">{{ entry.paper.title }}</a>
</p>
<p style="font-family:Georgia,'Times New Roman',serif; font-size:17px; color:#333; line-height:1.6; margin:0 0 4px 0;">{{ entry.abstract_excerpt or '' }}</p>
{% if entry.summary_source and entry.summary_source != 'extractive' %}
<p style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:11px; color:#bbb; margin:0 0 10px 0;">Summarized by {{ entry.summary_source }}</p>
{% elif entry.summary_source == 'extractive' %}
<p style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:11px; color:#bbb; margin:0 0 10px 0;">Abstract excerpt (not summarized)</p>
{% endif %}
<p style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:13px; color:#999; margin:0 0 {{ '28px' if not loop.last else '0' }};">
  <a href="{{ entry.paper.canonical_url }}" style="color:#2563eb; text-decoration:none;">Abstract</a>
  {% if entry.paper.pdf_url %}&nbsp;&middot;&nbsp;<a href="{{ entry.paper.pdf_url }}" style="color:#2563eb; text-decoration:none;">PDF</a>{% endif %}
  {% for label, url in entry.resource_links.items() %}&nbsp;&middot;&nbsp;<a href="{{ url }}" style="color:#2563eb; text-decoration:none;">{{ label }}</a>{% endfor %}
  &nbsp;&middot;&nbsp;{{ entry.category_labels | join(', ') }}
</p>
{% if not loop.last %}
<hr style="border:none; border-top:1px solid #f0f0f0; margin:0 0 24px 0;">
{% endif %}
{% endfor %}

{% if not loop.last %}
<div style="margin:52px 0;"></div>
{% endif %}
{% endfor %}

{% if not grouped %}
<p style="font-family:Georgia,serif; font-size:17px; color:#666;">No papers matched your criteria for this period.</p>
{% endif %}

<!-- Footer -->
<hr style="border:none; border-top:1px solid #eee; margin:28px 0 16px 0;">
<p style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; font-size:10px; color:#bbb; margin:0;">
  Generated by <a href="https://github.com/crlandsc/research-digest" style="color:#bbb;">research-digest</a> v{{ version }}
</p>

</td></tr>
</table>
</td></tr>
</table>
</body>
</html>
""",
    keep_trailing_newline=True,
)

_TEXT_TEMPLATE = Template(
    """\
{{ title }}
{{ generated_at }} - {{ total_papers }} paper{{ 's' if total_papers != 1 }}

{% for group_name, group_entries in grouped.items() %}
{{ group_name | upper }}
{{ '-' * group_name | length }}
{% for entry in group_entries %}
{{ entry.paper.title }}
{{ entry.abstract_excerpt or '' }}
{% if entry.summary_source and entry.summary_source != 'extractive' %}[Summarized by {{ entry.summary_source }}]
{% elif entry.summary_source == 'extractive' %}[Abstract excerpt]
{% endif %}{{ entry.paper.canonical_url }}
{% if entry.paper.pdf_url %}{{ entry.paper.pdf_url }}{% endif %}
{% for label, url in entry.resource_links.items() %}{{ label }}: {{ url }}
{% endfor %}

{% endfor %}
{% endfor %}
{% if not grouped %}
No papers matched your criteria for this period.
{% endif %}
Generated by research-digest v{{ version }}
""",
    keep_trailing_newline=True,
)


def render_email(
    entries: list[DigestEntry],
    config: AppConfig,
    total_reviewed: int = 0,
) -> tuple[str, str]:
    """Render digest as (html, plaintext) for email delivery."""
    grouped = _group_entries(entries)

    ctx = dict(
        title=config.digest.title,
        generated_at=datetime.now(timezone.utc).strftime("%B %d, %Y"),
        grouped=grouped,
        total_papers=len(entries),
        version=__version__,
    )

    # Jinja can't access private attrs, so we use a filter
    class _EntryProxy:
        """Wraps DigestEntry to add category_labels and resource_links for template."""
        def __init__(self, entry: DigestEntry):
            self._entry = entry
        def __getattr__(self, name: str):
            if name == "category_labels":
                return [category_label(c) for c in self._entry.paper.categories]
            if name == "resource_links":
                return self._entry.paper.resource_links
            return getattr(self._entry, name)

    proxied_groups = OrderedDict()
    for group_name, group_entries in grouped.items():
        proxied_groups[group_name] = [_EntryProxy(e) for e in group_entries]

    ctx["grouped"] = proxied_groups
    return (_EMAIL_TEMPLATE.render(**ctx), _TEXT_TEMPLATE.render(**ctx))
