"""HTML email rendering for digest delivery."""

from datetime import datetime, timezone

from jinja2 import Template

from research_digest import __version__
from research_digest.config import AppConfig
from research_digest.models import DigestEntry

_EMAIL_TEMPLATE = Template(
    """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body {
    font-family: Georgia, 'Times New Roman', serif;
    max-width: 520px;
    margin: 0 auto;
    padding: 24px 16px;
    color: #1a1a1a;
    line-height: 1.65;
    font-size: 15px;
  }
  h1 {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    font-size: 22px;
    margin: 0 0 4px 0;
    font-weight: 700;
  }
  .date {
    color: #888;
    font-size: 13px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    margin-bottom: 28px;
  }
  .paper {
    margin-bottom: 28px;
  }
  .paper-title {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    font-size: 16px;
    font-weight: 700;
    margin-bottom: 8px;
    line-height: 1.3;
  }
  .paper-title a {
    color: #1a1a1a;
    text-decoration: underline;
  }
  .paper-summary {
    font-size: 15px;
    color: #333;
    margin-bottom: 0;
  }
  .paper-links {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    font-size: 12px;
    margin-top: 8px;
    color: #888;
  }
  .paper-links a {
    color: #2563eb;
    text-decoration: none;
    margin-right: 10px;
  }
  hr {
    border: none;
    border-top: 1px solid #e5e5e5;
    margin: 28px 0;
  }
  .footer {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    color: #aaa;
    font-size: 11px;
    margin-top: 32px;
  }
  .footer a { color: #aaa; }
</style>
</head>
<body>

<h1>{{ title }}</h1>
<div class="date">{{ generated_at }} &middot; {{ entries | length }} paper{{ 's' if entries | length != 1 }}</div>

{% for entry in entries %}
<div class="paper">
  <div class="paper-title"><a href="{{ entry.paper.canonical_url }}">{{ entry.paper.title }}</a></div>
  <div class="paper-summary">{{ entry.abstract_excerpt or '' }}</div>
  <div class="paper-links">
    <a href="{{ entry.paper.canonical_url }}">Abstract</a>
    {% if entry.paper.pdf_url %}<a href="{{ entry.paper.pdf_url }}">PDF</a>{% endif %}
    &middot; {{ entry.paper.categories | join(', ') }}
  </div>
</div>
{% if not loop.last %}<hr>{% endif %}
{% endfor %}

{% if not entries %}
<p>No papers matched your criteria for this period.</p>
{% endif %}

<div class="footer">
  Generated by <a href="https://github.com/crlandsc/research-digest">research-digest</a> v{{ version }}
</div>

</body>
</html>
""",
    keep_trailing_newline=True,
)

_TEXT_TEMPLATE = Template(
    """\
{{ title }}
{{ generated_at }} - {{ entries | length }} paper{{ 's' if entries | length != 1 }}

{% for entry in entries %}
{{ entry.paper.title }}
{{ entry.abstract_excerpt or '' }}
{{ entry.paper.canonical_url }}
{% if entry.paper.pdf_url %}{{ entry.paper.pdf_url }}{% endif %}

{% endfor %}
{% if not entries %}
No papers matched your criteria for this period.
{% endif %}
Generated by research-digest v{{ version }}
""",
    keep_trailing_newline=True,
)


def render_email(
    entries: list[DigestEntry],
    config: AppConfig,
    total_reviewed: int = 0,
) -> tuple[str, str]:
    """Render digest as (html, plaintext) for email delivery."""
    ctx = dict(
        title=config.digest.title,
        generated_at=datetime.now(timezone.utc).strftime("%B %d, %Y"),
        entries=entries,
        version=__version__,
    )
    return (_EMAIL_TEMPLATE.render(**ctx), _TEXT_TEMPLATE.render(**ctx))
