"""Markdown digest rendering."""

import logging
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template

from research_digest import __version__
from research_digest.config import AppConfig
from research_digest.models import DigestEntry

logger = logging.getLogger(__name__)

_TEMPLATE = Template(
    """\
# {{ title }}

> Generated: {{ generated_at }}
> Run ID: {{ run_id }}
> Papers reviewed: {{ total_reviewed }} | Papers in digest: {{ entries | length }}

---
{% for entry in entries %}

## {{ entry.rank }}. {{ entry.paper.title }}

**Authors:** {{ entry.paper.authors | join(', ') }}
**Published:** {{ entry.paper.published_at.strftime('%Y-%m-%d') }}
**Categories:** {{ entry.paper.categories | join(', ') }}
**Score:** {{ "%.1f" | format(entry.score) }}
{% if entry.abstract_excerpt %}

> {{ entry.abstract_excerpt }}
{% if entry.summary_source and entry.summary_source != 'extractive' %}
_Summarized by {{ entry.summary_source }}_
{% elif entry.summary_source == 'extractive' %}
_Abstract excerpt (not summarized)_
{% endif %}
{% endif %}
{% if entry.reason %}

_Selected because: {{ entry.reason }}_
{% endif %}
{% if include_links %}

- [Abstract]({{ entry.paper.canonical_url }})
{% if entry.paper.pdf_url %}- [PDF]({{ entry.paper.pdf_url }})
{% endif %}{% if entry.paper.code_url %}- [Code]({{ entry.paper.code_url }})
{% endif %}
{% endif %}
---
{% endfor %}
{% if not entries %}
_No papers matched your criteria for this period._
{% endif %}

_Generated by research-digest v{{ version }}_
""",
    keep_trailing_newline=True,
)


def render_digest(
    entries: list[DigestEntry],
    config: AppConfig,
    run_id: str,
    total_reviewed: int = 0,
) -> str:
    """Render digest entries to a Markdown string."""
    return _TEMPLATE.render(
        title=config.digest.title,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        run_id=run_id[:8],
        total_reviewed=total_reviewed,
        entries=entries,
        include_links=config.digest.include_links,
        version=__version__,
    )


def write_digest(
    content: str,
    output_dir: str = "output",
    date_str: str | None = None,
) -> Path:
    """Write Markdown content to output/<date>/digest.md."""
    if date_str is None:
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = Path(output_dir) / date_str / "digest.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    logger.info("Digest written to %s", out)
    return out
